### ISSUE TITLE
Displaying folios on interface

### ISSUE THREAD

**Issue by SteveWLU** [wludh/huon_rails#65]
For displaying the folio numbers, is it possible that they not break the text, and appear in gray on the right (as they do now), but with the format "folio 2r" instead of "page: f.2r"

In the first laisse, for example, these lines should not have a space between them:

Mo la malvaxia ben à trovada la vie                                        folio 2r
(1V) De lui aver in soa camera alla çellie.

**Comment by walshbr** [comment]
Which laisse are you talking about?
I'll also need more description about the milestone attribute before I can update the parser. What are the different options?

**Comment by walshbr** [comment]
For example, right now I'm not seeing "folio" as an attribute, but I see "fol" - are all the milestones folio? Or are there multiple conversions that I'll need to know?

Also what do you mean by not breaking the text? 

<l n="1"><gap reason="missing folios" quantity="2"/><milestone n="1R" unit="fol."/>E perçò era Ugo d’Alvernia sevrie;</l>

Are you saying that you want the folio marker to appear on the right there, even though it appears at the beginning of the TEI line? That might be something that needs to just be encoded in the TEI itself. So in the above example, you would put the Milestone at the end of the line rather than at the beginning. Otherwise the TEI and the HTML-ready code that comes out on the other side would not really match up.

**Comment by SteveWLU** [comment]
I guess I have the milestone tag at the beginning of the line because technically that is where the page break occurs. If I put it at the end of the line, to someone reading the TEI, it makes it look like that line is the last of the previous folio. Does that make sense? 

By breaking the text, I mean that every time "fol. 2v" occurred over in the right margin, the lines would skip a space. Now I see that the foliation has been removed and the lines have no spaces where the folio breaks. Is it possible then to put back in the foliation in the format: "fol. 2V", etc.? Would then then require for the milestone to be at the end of the line?

**Comment by walshbr** [comment]
So like this? for that first laisse? Should probably talk on slack if you're around today just so i'm on the same page.

Mo la malvaxia ben à trovada la vie
De lui aver in soa camera alla çellie. fol. 2V

blah blah more Italian blah blah
